// Synthetic demo records. Dates are generated relative to today so the demo
// always shows a live-looking 30 day window. These never represent real
// charges, and are labelled as sample data throughout the interface.

import { addDays, addMonthsPreservingAnchor, parseISODate, todayISO, toISODate } from "./dates";
import type { Commitment, FieldClaim, TermVersion } from "./types";

const now = () => new Date().toISOString();

function claim(
  field: string,
  label: string,
  value: string | null,
  origin: FieldClaim["origin"],
  verification: FieldClaim["verification"],
  daysAgo: number,
  excerpt?: string,
  unknownReason?: FieldClaim["unknownReason"],
): FieldClaim {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return {
    field,
    label,
    value,
    origin,
    verification,
    capturedAt: d.toISOString(),
    excerpt,
    unknownReason,
  };
}

function term(
  id: string,
  amountMinor: number | null,
  currency: string,
  intervalCount: number,
  intervalUnit: TermVersion["recurrence"] extends null ? never : "day" | "week" | "month" | "year",
  anchorDate: string,
  effectiveFrom: string,
  extra: Partial<TermVersion> = {},
): TermVersion {
  return {
    id,
    amountMinor,
    currency,
    recurrence: { intervalCount, intervalUnit, anchorDate },
    effectiveFrom,
    effectiveTo: null,
    ...extra,
  };
}

/** Day-of-month anchored date in the next month or two, clamped to real days. */
function anchoredNext(anchorDay: number, monthsAhead = 0): string {
  const t = parseISODate(todayISO());
  const base = toISODate(new Date(Date.UTC(t.getUTCFullYear(), t.getUTCMonth(), 1)));
  return addMonthsPreservingAnchor(base, monthsAhead, anchorDay);
}

export function buildSampleCommitments(): Commitment[] {
  const today = todayISO();
  const d = (n: number) => addDays(today, n);

  const records: Commitment[] = [
    {
      id: "atlas-studio",
      merchant: "Atlas Studio",
      merchantDomain: "atlasstudio.example",
      manageUrl: "https://atlasstudio.example/account/billing",
      planNickname: "Pro monthly (trial)",
      category: "Design tools",
      channel: "web",
      lifecycle: "trial",
      intention: "review",
      cancellation: "not_started",
      terms: term("atlas-v1", 1200, "EUR", 1, "month", d(9), addDays(today, -21)),
      termHistory: [],
      nextBillDate: d(9),
      nextBillEstimated: false,
      trialEndDate: d(9),
      actionCutoffDate: null,
      reviewTargetDate: d(6),
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/Dublin",
      claims: [
        claim(
          "amount",
          "Recurring amount",
          "€12.00 per month",
          "browser_checkout",
          "confirmed",
          21,
          "“After your 30-day trial, your plan renews at €12/month.”",
        ),
        claim("trial_end", "Trial end", "Date captured at checkout", "confirmation_page", "confirmed", 21, "“Your free trial ends on this date.”"),
        claim(
          "cutoff",
          "Merchant action cutoff",
          null,
          "manual",
          "unconfirmed",
          21,
          undefined,
          "no_evidence",
        ),
      ],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Captured at checkout", detail: "Simulated browser checkout capture." },
      ],
      createdAt: now(),
      sample: true,
    },
    {
      id: "northwind-annual",
      merchant: "Northwind Archive",
      merchantDomain: "northwind.example",
      manageUrl: "https://northwind.example/members/plan",
      planNickname: "Annual membership",
      category: "Research",
      channel: "web",
      lifecycle: "active",
      intention: "cancel",
      cancellation: "not_started",
      terms: term("north-v2", 18000, "EUR", 1, "year", d(58), addDays(today, -300), {
        note: "Price rose from €150 to €180 at the last renewal.",
      }),
      termHistory: [
        term("north-v1", 15000, "EUR", 1, "year", d(58), addDays(today, -730), {
          effectiveTo: addDays(today, -301),
        }),
      ],
      // Notice must be given 30 days before the bill: the action leads.
      nextBillDate: d(58),
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: d(28),
      reviewTargetDate: d(26),
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: 30,
      merchantTimezone: "Europe/London",
      claims: [
        claim("amount", "Recurring amount", "€180.00 per year", "receipt", "confirmed", 300, "“Annual membership — €180.00”"),
        claim("cutoff", "Merchant action cutoff", "30 days notice before renewal", "provider_notice", "confirmed", 120, "“Cancellations require 30 days written notice before the renewal date.”"),
        claim("bill_date", "Next billing date", "Annual renewal date", "receipt", "confirmed", 300),
      ],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Added from a receipt" },
        { id: "h2", at: now(), kind: "terms_revised", summary: "Price revised €150 → €180", detail: "Applies to future renewals only. Historical bills keep the old price." },
        { id: "h3", at: now(), kind: "intention_changed", summary: "Intention changed to Cancel" },
      ],
      createdAt: now(),
      sample: true,
    },
    {
      id: "lumen-fitness",
      merchant: "Lumen Fitness",
      planNickname: "Premium (App Store)",
      category: "Health",
      channel: "apple_app_store",
      lifecycle: "trial",
      intention: "cancel",
      cancellation: "in_progress",
      terms: term("lumen-v1", 999, "EUR", 1, "month", d(3), addDays(today, -4)),
      termHistory: [],
      nextBillDate: d(3),
      nextBillEstimated: false,
      trialEndDate: d(3),
      actionCutoffDate: d(2),
      reviewTargetDate: d(0),
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/Dublin",
      claims: [
        claim("amount", "Recurring amount", "€9.99 per month", "screenshot", "confirmed", 4),
        claim("cutoff", "Merchant action cutoff", "Apple guidance: at least 24 hours before the trial ends", "provider_notice", "unconfirmed", 4, "Apple publishes a 24-hour guideline; exact timing remains subject to the verified source."),
      ],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Added manually from a screenshot" },
        { id: "h2", at: now(), kind: "assistance_opened", summary: "Opened Apple cancellation guidance", detail: "Opening assistance does not mean the subscription is canceled." },
      ],
      createdAt: now(),
      sample: true,
    },
    {
      id: "harbor-news",
      merchant: "Harbor News",
      merchantDomain: "harbornews.example",
      manageUrl: "https://harbornews.example/account",
      planNickname: "Digital, billed every 4 weeks",
      category: "News",
      channel: "web",
      lifecycle: "active",
      intention: "review",
      cancellation: "not_started",
      terms: term("harbor-v1", 700, "GBP", 4, "week", d(11), addDays(today, -200)),
      termHistory: [],
      nextBillDate: d(11),
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: null,
      reviewTargetDate: d(8),
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/London",
      claims: [
        claim("amount", "Recurring amount", "£7.00 every 4 weeks", "email", "confirmed", 200, "“£7 every 4 weeks”"),
        claim("interval", "Billing interval", "Every 4 weeks — 13 charges in a 364-day reference year", "email", "confirmed", 200),
      ],
      history: [{ id: "h1", at: now(), kind: "created", summary: "Added from a billing email" }],
      createdAt: now(),
      sample: true,
    },
    {
      id: "pinecone-cloud",
      merchant: "Pinecone Cloud",
      merchantDomain: "pineconecloud.example",
      planNickname: "Usage-based workspace",
      category: "Developer tools",
      channel: "web",
      lifecycle: "active",
      intention: "keep",
      cancellation: "not_started",
      terms: {
        id: "pine-v1",
        amountMinor: null,
        amountUnknownReason: "variable_amount",
        currency: "USD",
        recurrence: { intervalCount: 1, intervalUnit: "month", anchorDate: anchoredNext(31) },
        effectiveFrom: addDays(today, -120),
        effectiveTo: null,
      },
      termHistory: [],
      nextBillDate: anchoredNext(31, 1),
      nextBillEstimated: true,
      trialEndDate: null,
      actionCutoffDate: null,
      reviewTargetDate: null,
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "America/New_York",
      claims: [
        claim("amount", "Recurring amount", null, "transaction", "unconfirmed", 30, undefined, "variable_amount"),
        claim("anchor", "Billing anchor", "31st of the month, clamped to the last valid day in shorter months", "manual", "confirmed", 120),
      ],
      history: [{ id: "h1", at: now(), kind: "created", summary: "Added manually" }],
      createdAt: now(),
      sample: true,
    },
    {
      id: "verdant-box",
      merchant: "Verdant Box",
      merchantDomain: "verdantbox.example",
      planNickname: "Monthly plant box",
      category: "Home",
      channel: "unknown",
      lifecycle: "active",
      intention: "cancel",
      cancellation: "not_started",
      terms: term("verdant-v1", 2450, "EUR", 1, "month", d(-2), addDays(today, -95)),
      termHistory: [],
      nextBillDate: d(28),
      nextBillEstimated: true,
      trialEndDate: null,
      // Cutoff already passed: window-passed messaging, not a false promise.
      actionCutoffDate: d(-4),
      reviewTargetDate: d(-6),
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/Amsterdam",
      claims: [
        claim("amount", "Recurring amount", "€24.50 per month", "manual", "unconfirmed", 95),
        claim("channel", "Purchase channel", null, "manual", "unconfirmed", 95, undefined, "no_evidence"),
      ],
      history: [{ id: "h1", at: now(), kind: "created", summary: "Added manually" }],
      createdAt: now(),
      sample: true,
    },
    {
      id: "cobalt-vpn",
      merchant: "Cobalt VPN",
      merchantDomain: "cobaltvpn.example",
      manageUrl: "https://cobaltvpn.example/dashboard/subscription",
      planNickname: "2-year plan",
      category: "Security",
      channel: "web",
      lifecycle: "active",
      intention: "review",
      cancellation: "not_started",
      terms: term("cobalt-v1", 8900, "USD", 2, "year", d(400), addDays(today, -330)),
      termHistory: [],
      nextBillDate: d(400),
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: null,
      // No target set: this is the "needs a date" case for a long-dated plan.
      reviewTargetDate: null,
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "America/Los_Angeles",
      claims: [
        claim("amount", "Recurring amount", "$89.00 every 2 years", "receipt", "confirmed", 330),
        claim("cutoff", "Merchant action cutoff", null, "manual", "unconfirmed", 330, undefined, "merchant_terms_unclear"),
      ],
      history: [{ id: "h1", at: now(), kind: "created", summary: "Added from a receipt" }],
      createdAt: now(),
      sample: true,
    },
    {
      id: "slate-storage",
      merchant: "Slate Storage",
      merchantDomain: "slatestorage.example",
      planNickname: "2 TB plan (paused)",
      category: "Storage",
      channel: "web",
      lifecycle: "paused",
      intention: "review",
      cancellation: "not_started",
      terms: term("slate-v1", 999, "EUR", 1, "month", d(15), addDays(today, -400)),
      termHistory: [],
      // Paused with no known resume rule: projection suspended, uncertainty visible.
      nextBillDate: null,
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: null,
      reviewTargetDate: null,
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/Dublin",
      claims: [
        claim("amount", "Recurring amount", "€9.99 per month", "receipt", "confirmed", 400),
        claim("resume", "Resume rule", null, "manual", "unconfirmed", 20, undefined, "no_evidence"),
      ],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Added from a receipt" },
        { id: "h2", at: now(), kind: "manual_correction", summary: "Lifecycle set to Paused", detail: "Projection suspended while the resume rule is unknown." },
      ],
      createdAt: now(),
      sample: true,
    },
    {
      id: "meridian-music",
      merchant: "Meridian Music",
      planNickname: "Family (App Store)",
      category: "Entertainment",
      channel: "apple_app_store",
      lifecycle: "active",
      intention: "keep",
      cancellation: "not_started",
      terms: term("meridian-v1", 1699, "EUR", 1, "month", d(19), addDays(today, -500)),
      termHistory: [],
      nextBillDate: d(19),
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: null,
      reviewTargetDate: null,
      accessEndDate: null,
      renewalStopDate: null,
      noticePeriodDays: null,
      merchantTimezone: "Europe/Dublin",
      claims: [claim("amount", "Recurring amount", "€16.99 per month", "receipt", "confirmed", 500)],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Added manually" },
        { id: "h2", at: now(), kind: "intention_changed", summary: "Intention set to Keep", detail: "A deliberate Keep is a valid outcome." },
      ],
      createdAt: now(),
      sample: true,
    },
    {
      id: "quill-writing",
      merchant: "Quill Writing",
      merchantDomain: "quill.example",
      manageUrl: "https://quill.example/settings/subscription",
      planNickname: "Standard monthly",
      category: "Productivity",
      channel: "web",
      lifecycle: "active",
      intention: "cancel",
      cancellation: "confirmed",
      terms: term("quill-v1", 800, "EUR", 1, "month", d(12), addDays(today, -180)),
      termHistory: [],
      nextBillDate: null,
      nextBillEstimated: false,
      trialEndDate: null,
      actionCutoffDate: null,
      reviewTargetDate: null,
      accessEndDate: d(12),
      renewalStopDate: addDays(today, -1),
      noticePeriodDays: null,
      merchantTimezone: "Europe/Dublin",
      claims: [
        claim("amount", "Recurring amount", "€8.00 per month", "receipt", "confirmed", 180),
        claim("cancellation", "Cancellation", "Confirmed by you", "manual", "confirmed", 1, "You confirmed you completed cancellation with the provider."),
      ],
      history: [
        { id: "h1", at: now(), kind: "created", summary: "Added manually" },
        { id: "h2", at: now(), kind: "assistance_opened", summary: "Opened the provider's management page" },
        { id: "h3", at: now(), kind: "cancellation_confirmed", summary: "Cancellation confirmed by you", detail: "Renewal stopped. Access continues until the access end date." },
      ],
      createdAt: now(),
      sample: true,
    },
  ];

  return records;
}
