/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpendingRouteImport } from './routes/spending'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as CaptureImportRouteImport } from './routes/capture/import'
import { Route as DemoCheckoutRouteImport } from './routes/demo/checkout'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions.index'
import { Route as SubscriptionsIdRouteImport } from './routes/subscriptions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingRoute = SpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureImportRoute = CaptureImportRouteImport.update({
  id: '/capture/import',
  path: '/capture/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCheckoutRoute = DemoCheckoutRouteImport.update({
  id: '/demo/checkout',
  path: '/demo/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIdRoute = SubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/discovery': typeof DiscoveryRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/upcoming': typeof UpcomingRoute
  '/capture/import': typeof CaptureImportRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/discovery': typeof DiscoveryRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/upcoming': typeof UpcomingRoute
  '/capture/import': typeof CaptureImportRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/discovery': typeof DiscoveryRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/upcoming': typeof UpcomingRoute
  '/capture/import': typeof CaptureImportRoute
  '/demo/checkout': typeof DemoCheckoutRoute
  '/subscriptions/$id': typeof SubscriptionsIdRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/calendar'
    | '/discovery'
    | '/onboarding'
    | '/review'
    | '/settings'
    | '/spending'
    | '/upcoming'
    | '/capture/import'
    | '/demo/checkout'
    | '/subscriptions/$id'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/auth'
    | '/calendar'
    | '/discovery'
    | '/onboarding'
    | '/review'
    | '/settings'
    | '/spending'
    | '/upcoming'
    | '/capture/import'
    | '/demo/checkout'
    | '/subscriptions/$id'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/calendar'
    | '/discovery'
    | '/onboarding'
    | '/review'
    | '/settings'
    | '/spending'
    | '/upcoming'
    | '/capture/import'
    | '/demo/checkout'
    | '/subscriptions/$id'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DiscoveryRoute: typeof DiscoveryRoute
  OnboardingRoute: typeof OnboardingRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SpendingRoute: typeof SpendingRoute
  UpcomingRoute: typeof UpcomingRoute
  CaptureImportRoute: typeof CaptureImportRoute
  DemoCheckoutRoute: typeof DemoCheckoutRoute
  SubscriptionsIdRoute: typeof SubscriptionsIdRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending': {
      id: '/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof SpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/import': {
      id: '/capture/import'
      path: '/capture/import'
      fullPath: '/capture/import'
      preLoaderRoute: typeof CaptureImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/checkout': {
      id: '/demo/checkout'
      path: '/demo/checkout'
      fullPath: '/demo/checkout'
      preLoaderRoute: typeof DemoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/$id': {
      id: '/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof SubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DiscoveryRoute: DiscoveryRoute,
  OnboardingRoute: OnboardingRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SpendingRoute: SpendingRoute,
  UpcomingRoute: UpcomingRoute,
  CaptureImportRoute: CaptureImportRoute,
  DemoCheckoutRoute: DemoCheckoutRoute,
  SubscriptionsIdRoute: SubscriptionsIdRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
